Esm (#7)
* wip

* tidy

* fix compile errors

* fix compile errors

* fix event

* make EOL a getter

* migrate tests to esm

* remove use strict pragma

* remove git hook

* fix streams

* fix streams

* remove streamx dep

* use buffer module

* use esm exports in streams

* use esm exports in fs/streams

* default export for stream

* fix package.json

* defaults

* fix imports

* fix imports

* fix failing test

* dont use node as platform

* automatically stringify

* revert node as platform

* add build

* fix(): fix imports and actually run tests

* add build

* remove prepublish

* fix imports

* fix os import

* refactor(os): just make 'os.EOL' eval'd at export time

* refactor(fs,exports): more fs tests, named fs.constants, rework exports

* call super

* feat(fs): introduce AbortSignal in readFile/writeFile

* refactor(fs/promises): include readFile/writeFile

* refactor(fs/promises): remove usage of 'mode' for readFile/writeFile

* refactor(fs/promises): await for callstack capture

* feat(fs): introduce 'chmod'

* fix param key

* handle error

* fix method name

* oops

* refactor(ipc): return 'Result' for internal ipc

* fix(ipc): fix resolved 'Result' in 'ipc.request()'

* refactor(ipc,errors): intelligently create IPC result errors

* no params on bt ctor

* fix(errors): ensure errors have the right name

* refactor(ipc): capture stack trace from caller when possible

* dont use random uuids

* remove uuid from deps

* refactor(ipc,errors): introduce IPC timeout errors

* fix(ipc): ensure cleanup in ipc.request()

* test(os): introduce tests of 'os'

* test(os): add 'os.EOL' test

* refactor(ipc,fs): use level 1 AbortSignal 'abort' event

* refactor(ipc,fs): throw on already aborted signal

* fix events

* fix(errors): fix undefined reference to 'signal'

* refactor(fs/handle): clean up ref to 'signal'

* fix(ipc): make 'ipc.write()' timeout opt-in

* refactor(ipc): clean up

* more wip bt

Co-authored-by: Sergey Rubanov <chi187@gmail.com>
Co-authored-by: Joseph Werle <joseph.werle@gmail.com>